const users = [
  {
    id: 1,
    name: "Pietro",
    surname: "Di Stefano",
    username: "pietro23",
    email: "pietrodistefano@gmail.com",
    pic: "",
    password: "coding",
    social: {
      linkedin: "",
      github: "",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    creditCard: null,
    balance: null,
    isLogged: false,
  },
  {
    id: 2,
    name: "Cesare",
    surname: "Tomasello",
    username: "cesare28",
    email: "cesaretomasello@gmail.com",
    pic: "",
    password: "coding",
    social: {
      linkedin: "",
      github: "",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    creditCard: null,
    balance: null,
    isLogged: false,
  },
  {
    id: 3,
    name: "Sebastiano",
    surname: "Occhipinti",
    username: "sebastiano24",
    email: "sebastianoochhipinti@gmail.com",
    pic: "",
    password: "coding",
    social: {
      linkedin: "",
      github: "",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    creditCard: null,
    balance: null,
    isLogged: false,
  },
  {
    id: 4,
    name: "Marco",
    surname: "Rivera",
    username: "marco29",
    email: "marcorivera@gmail.com",
    pic: "",
    password: "coding",
    social: {
      linkedin: "",
      github: "",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    creditCard: null,
    balance: null,
    isLogged: false,
  },
  {
    id: 5,
    name: "Chiara",
    surname: "Maggio",
    username: "magichiara",
    email: "info.chiaramaggio@gmail.com",
    pic: "/profile_pics/chiara.jpg",
    password: "coding",
    social: {
      linkedin: "https://www.linkedin.com/in/chiaramaggio",
      github: "https://github.com/magichiara",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    isLogged: false,
  },
  {
    id: 6,
    name: "Giuseppe",
    surname: "Senettone",
    username: "Senex30",
    email: "giuseppesenettone@gmail.com",
    pic: "",
    password: "coding",
    social: {
      linkedin: "",
      github: "",
    },
    assets: {
      coins: [],
      nft: [],
    },
    cart: [],
    creditCard: null,
    balance: null,
    isLogged: false,
  },
];

export default users;
