import { useState, useEffect } from "react";
import Head from "next/head";
import CryptoCoins from "@/components/cryptocoins/CryptoCoins";
import FavoriteCoins from "@/components/favoriteCoins/FavoriteCoins";
import Cart from "@/components/cart/Cart";
import styles from "@/styles/Home.module.scss";
import Loader from "../components/loader/Loader";

export default function Home({ coins }) {
  const [cartModal, setCartModal] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  return (
    <>
      <Head>
        <title>Crypto Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <Loader />
      ) : (
        <main className={styles.main}>
          <div>
            <CryptoCoins data={coins} />
          </div>
          <div>
            <FavoriteCoins setCartModal={setCartModal} />
          </div>
          <>
            {/* MODAL --> CART */}
            {cartModal && <Cart setCartModal={setCartModal} coins={coins} />}
          </>
        </main>
      )}
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`https://api.coingecko.com/api/v3/search/trending`);
  const coins = await res.json();

  return {
    props: {
      coins,
    },
  };
}
